Repository pycontribs/python-vagrant, pull requests merged in 2022-12, with the labels that each got.

#143 Remove comments from flake8 extend-ignore
  .flake8
Labels: bug

#142 Allowlist in glob style
  tox.ini
Labels: bug, skip-changelog

#144 Use pip-compile
  .github/dependabot.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  requirements.txt
  tox.ini
Labels: skip-changelog

#146 Adopt PEP-621
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
  setup.cfg
  tox.ini
Labels: bug

#147 Migrated tool configs to pyproject.toml
  .pylintrc
  MANIFEST.in
  mypy.ini
  pyproject.toml
Labels: skip-changelog

#148 Deprecate python 3.8 and add python 3.11
  .github/workflows/release.yml
  .github/workflows/tox.yml
  README.md
  pyproject.toml
Labels: enhancement, test
