Repository pycontribs/python-vagrant, pull requests merged in 2022-03, with the labels that each got.

#74 Add initial pre-commit config
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  tests/test_vagrant.py
  tests/vagrantfiles/multivm_Vagrantfile
  tox.ini
  vagrant/__init__.py
Labels: skip-changelog

#75 pre-commit: enable prettier
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
Labels: skip-changelog

#73 Add reusable GHA pipelines
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: skip-changelog

#76 Add initial tox pipeline
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#77 Require py37+ and adopt PEP-517 packaging
  .github/workflows/tox.yml
  .gitignore
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: major

#78 chore: populate codeowners
  .github/CODEOWNERS
Labels: skip-changelog

#79 chore: enable black
  .pre-commit-config.yaml
  tests/test_vagrant.py
  tests/test_vagrant_test_case.py
  vagrant/__init__.py
  vagrant/test.py
Labels: skip-changelog

#80 chore: replace nose with pytest
  README.md
  pyproject.toml
  setup.cfg
  tests/test_vagrant.py
  tox.ini
Labels: skip-changelog

#81 Fix logging deprecation
  vagrant/__init__.py
Labels: bug

#82 Run the CI on macos
  .github/workflows/tox.yml
Labels: skip-changelog

#83 Update box used for testing
  .github/workflows/tox.yml
  tests/test_vagrant.py
  tests/test_vagrant_test_case.py
  tests/vagrantfiles/multi_box/Vagrantfile
  tests/vagrantfiles/multivm_Vagrantfile
  tests/vagrantfiles/shell_provision_Vagrantfile
  tests/vagrantfiles/single_box/Vagrantfile
  tests/vagrantfiles/vm_Vagrantfile
  vagrant/__init__.py
Labels: skip-changelog

#86 test: fix setUpOnce
  vagrant/test.py
Labels: skip-changelog

#85 configure vbguest.auto_update and correct vm.box
  tests/vagrantfiles/multi_box/Vagrantfile
Labels: skip-changelog

#87 Replace TD global with a fixture
  tests/test_vagrant.py
  tox.ini
Labels: skip-changelog

#90 Drop support for py37
  .github/workflows/tox.yml
  setup.cfg
Labels: major

#91 Enable flake8
  .flake8
  .pre-commit-config.yaml
  tests/test_vagrant.py
  tests/test_vagrant_test_case.py
  vagrant/__init__.py
  vagrant/test.py
Labels: skip-changelog

#92 Enable pylint
  .pre-commit-config.yaml
  .pylintrc
  tests/test_vagrant.py
  vagrant/__init__.py
  vagrant/test.py
Labels: skip-changelog

#94 Declare vagrant package as typed
  .pre-commit-config.yaml
  mypy.ini
  setup.cfg
  vagrant/py.typed
  vagrant/test.py
Labels: enhancement

#89 Fix vm name in SpecificMultiBoxTests
  tests/test_vagrant_test_case.py
Labels: skip-changelog

#93 Fix vagrant output parsing
  vagrant/__init__.py
Labels: bug

#96 ignore failed destroy command if there's no environment
  tests/test_vagrant.py
Labels: skip-changelog

#99 Ensure box remove uses force
  vagrant/__init__.py
Labels: bug

#103 Fix streaming with python3+
  tests/test_vagrant.py
  vagrant/__init__.py
Labels: bug

#101 Fixed main README
  README.md
Labels: bug

#102 test_boxesvm: Fix dummy box handling
  tests/test_vagrant.py
  tests/tools/create_dummy_box.sh
  tox.ini
Labels: skip-changelog

#105 Create FUNDING.yml
  .github/FUNDING.yml
Labels: skip-changelog

#104 Enable code coverage
  .github/workflows/tox.yml
  codecov.yml
  pytest.ini
  setup.cfg
  tox.ini
Labels: skip-changelog

#106 Prevent leftovers after testing
  .gitignore
  tox.ini
Labels: skip-changelog

#107 Fix test regression from #104
  tox.ini
Labels: bug, skip-changelog

#108 Update FUNDING.yml
  .github/FUNDING.yml
Labels: skip-changelog

#111 use vm_name as first positional argument in up()
  vagrant/__init__.py
Labels: major

#97 Add additional .flake8 ignores and fix S607/B607
  .flake8
  tests/test_vagrant.py
Labels: skip-changelog

#100 add `vagrant validate`
  tests/test_vagrant.py
  vagrant/__init__.py
Labels: enhancement

#114 Update README.md
  README.md
Labels: bug

#115 configure vbguest and validate Vagrantfile during lifecycle test
  tests/test_vagrant.py
Labels: enhancement

#116 Adopt src code layout
  setup.cfg
  src/vagrant/__init__.py
  src/vagrant/compat.py
  src/vagrant/py.typed
  src/vagrant/test.py
  tox.ini
Labels: enhancement

#118 Ensure use of setuptools-scm version
  .gitignore
  pyproject.toml
  src/vagrant/__init__.py
Labels: bug

#120 Spelling and links
  README.md
  src/vagrant/__init__.py
  src/vagrant/compat.py
  tests/test_vagrant.py
Labels: skip-changelog
